# Generated by Django 5.1.3 on 2024-11-21 07:39

from django.db import migrations
from django.contrib.auth.models import Group, Permission

def create_roles_and_groups(apps, schema_editor):
    Role = apps.get_model('authentication', 'Role')
    User = apps.get_model('authentication', 'User')

    # Créer les roles
    roles = {
        'Administration',
        'Maintenance',
        'Production',
    }

    for role_name in roles:
        role, created = Role.objects.get_or_create(name=role_name)
        # Créer les groupes
        group, created = Group.objects.get_or_create(name=role_name)

    # Ajouter les permissions au groupe
    """for perm in perms:
        permission = Permission.objects.get(codename=perm)
        group.permissions.add(permission)"""
    
    # Assigner les utilisateurs aux groupes et aux rôles
    
    for user in User.objects.all():
        if user.role:
            group = Group.objects.get(name=user.role.name)
            user.groups.add(group)
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles_and_groups)
    ]
